- name: ArgoCD 셋업
  hosts: main-master
  become: false
  tasks:
    - name: ArgoCD용 Namespace 생성
      kubernetes.core.k8s:
        name: "argocd"
        kind: Namespace
        state: present
        kubeconfig: /home/ec2-user/.kube/config

    - name: ArgoCD Helm 리포지토리 추가
      kubernetes.core.helm_repository:
        name: argo
        repo_url: "https://argoproj.github.io/argo-helm"

    - name: Helm 리포지토리 업데이트
      command: helm repo update

    - name: LBC Webhook 설정 삭제
      shell: |
        kubectl delete mutatingwebhookconfigurations mservice.elbv2.k8s.aws --ignore-not-found
        kubectl delete validatingwebhookconfigurations vservice.elbv2.k8s.aws --ignore-not-found
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config
      ignore_errors: yes

    - name: ArgoCD 설치
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        release_namespace: "argocd"
        create_namespace: true
        wait: true
        values:
          server:
            service:
              type: NodePort
              nodePorts:
                http: 30080
            extraArgs:
              - --insecure

    - name: CRD 존재 확인
      kubernetes.core.k8s_info:
        kind: CustomResourceDefinition
        name: applications.argoproj.io
      register: crd_info
      until: crd_info.resources | length > 0
      retries: 10
      delay: 5

    - name: ArgoCD root Application 생성
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: root-app
            namespace: argocd
          spec:
            project: default
            source:
              repoURL: https://github.com/kanei0415/ktcloud-k8s-argocd-manifest.git
              targetRevision: HEAD
              path: Setup
            destination:
              server: https://kubernetes.default.svc
              namespace: default
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
