- name: Helm 셋업
  hosts: main-master
  become: true
  vars:
    helm_version: "v3.14.0"
    arch: "amd64"

  tasks:
    - name: Helm 설치
      unarchive:
        src: "https://get.helm.sh/helm-{{ helm_version }}-linux-{{ arch }}.tar.gz"
        dest: /tmp
        remote_src: true

    - name: Helm 바이너리를 /usr/local/bin에 복사
      copy:
        src: "/tmp/linux-{{ arch }}/helm"
        dest: /usr/local/bin/helm
        mode: "0755"
        remote_src: true

    - name: Helm 설치 확인
      command: helm version
      register: helm_result
