- name: Kubernetes 패키지 설치
  hosts: all
  become: true
  tasks:
    - name: Kubernetes 리포지토리 추가
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        mode: "0644"
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key

    - name: dnf 캐시 정리
      ansible.builtin.shell: dnf clean all
      become: true

    - name: kubelet, kubeadm, kubectl 설치
      ansible.builtin.dnf:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: kubelet 서비스 활성화
      ansible.builtin.systemd:
        name: kubelet
        enabled: true
