- name: Kubernetes 클러스터 사전 조건 설정
  hosts: all
  become: true
  tasks:
    - name: 스왑 비활성화
      ansible.builtin.command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: 커널 모듈 로드
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: 브리지 네트워크 설정 적용
      ansible.builtin.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: "1"
        state: present

    - name: /etc/hosts 파일에 마스터 노드 항목 추가
      lineinfile:
        path: /etc/hosts
        line: "{{ item.ip }} {{ item.name }}"
      loop:
        - { ip: "{{ a_master_01_private_ip }}", name: "a-master-01" }
        - { ip: "{{ a_master_02_private_ip }}", name: "a-master-02" }
        - { ip: "{{ b_master_01_private_ip }}", name: "b-master-01" }
